import type { AgendaAppointment } from "@/components/agenda/AgendaCalendar";

/** Historical and upcoming fixtures for the showroom only. */
export const demoAgendaHistory: AgendaAppointment[] = [
  {
    id: "demo-agenda-28",
    dateKey: "2026-09-28",
    weekday: "lunes",
    dateLabel: "28 sept 2026",
    startTime: "09:00",
    endTime: "10:00",
    patient: "Mariana López",
    service: "Consulta psicológica",
    status: "cancelled",
    paid: true,
  },
  {
    id: "demo-agenda-29",
    dateKey: "2026-09-29",
    weekday: "martes",
    dateLabel: "29 sept 2026",
    startTime: "11:00",
    endTime: "11:50",
    patient: "Tomás Méndez",
    service: "Sesión de seguimiento",
    status: "cancelled",
    paid: false,
  },
  {
    id: "demo-agenda-30",
    dateKey: "2026-09-30",
    weekday: "miércoles",
    dateLabel: "30 sept 2026",
    startTime: "10:30",
    endTime: "11:45",
    patient: "Carlos Ruiz",
    service: "Primera consulta",
    status: "completed",
    paid: true,
  },
  {
    id: "demo-agenda-01",
    dateKey: "2026-10-01",
    weekday: "jueves",
    dateLabel: "1 oct 2026",
    startTime: "14:00",
    endTime: "15:00",
    patient: "Lucía Pérez",
    service: "Consulta psicológica",
    status: "cancelled",
    paid: false,
  },
  {
    id: "demo-agenda-02",
    dateKey: "2026-10-02",
    weekday: "viernes",
    dateLabel: "2 oct 2026",
    startTime: "16:00",
    endTime: "17:15",
    patient: "Carlos Ruiz",
    service: "Primera consulta",
    status: "cancelled",
    paid: false,
  },
  {
    id: "demo-agenda-04",
    dateKey: "2026-10-04",
    weekday: "domingo",
    dateLabel: "4 oct 2026",
    startTime: "10:00",
    endTime: "10:50",
    patient: "Tomás Méndez",
    service: "Sesión de seguimiento",
    status: "scheduled",
    paid: true,
  },
];
