"use client";
import Link from "next/link";
import AppTopbar from "@/components/layout/AppTopbar";
import AppMobileNav from "@/components/layout/AppMobileNav";
import { appNav, navItems, profileTabs, type NavKey, type ProfileSectionTab } from "@/components/layout/AppNav";
import { Tabs } from "@/components/crm/CrmUi";
import { DemoDashboard, DemoFollowUps, useShowroom } from "./showroom";
import { DemoAutomations, DemoBell, DemoNotifications } from "./automation-views";
import { demoServices as initialServices, demoAppointments as initialAppointments, demoPatients as patients } from "./showroom-data";
import { DemoAgenda } from "./agenda";
import { DemoPatients } from "./patients";
import { demoPatientId } from "./crm-data";
import BellisLogo from "@/components/brand/BellisLogo";
import { formatMoney } from "@/lib/market";
import "./demo.css";
import "../dashboard/live.css";
import "../pacientes/crm.css";
import "../pacientes/crm-phase2.css";
import "../automatizaciones/automations.css";
import "../notificaciones/notifications.css";
import "./showroom.css";
import { useState } from "react";
import { FileText, Clock3, ArrowUpRight, Plus, Check, ExternalLink } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { QuestionnaireBuilder } from "./questionnaire-builder";
import { PreconsultationSummary } from "./preconsultation-summary";
import { starterQuestionnaire, type QuestionnaireAnswers } from "@/lib/questionnaires/model";

// Same navigation as the product; here every entry switches a mock section instead of a route.
type Section = NavKey;

export default function Demo(){
  const showroom = useShowroom();
  const [section,setSection]=useState<Section>("Resumen"); const [services,setServices]=useState(initialServices); const [appointments,setAppointments]=useState(initialAppointments); const [selected,setSelected]=useState<number|null>(null); const [profile,setProfile]=useState<string|null>(null); const [fromFollowUps,setFromFollowUps]=useState(false); const [profileTab,setProfileTab]=useState<ProfileSectionTab>("perfil"); const [newService,setNewService]=useState({name:"",price:"",duration:"60",mode:"Online"}); const [created,setCreated]=useState(false); const [days,setDays]=useState([true,true,true,true,true,false,false]); const [paymentLink,setPaymentLink]=useState("");const [paymentProvider,setPaymentProvider]=useState("mercado_pago_ar"); const [saved,setSaved]=useState(false);
  const addService=()=>{if(!newService.name.trim()||Number(newService.price)<=0)return;setServices([...services,{name:newService.name,price:Number(newService.price),duration:Number(newService.duration),mode:newService.mode,active:true}]);setNewService({name:"",price:"",duration:"60",mode:"Online"});setCreated(false)};
  const selectedPatient = selected === null ? undefined : patients.find(patient => patient.name === appointments[selected].name);
  const showPatient = (name: string, origin?: "Seguimientos") => { setProfile(demoPatientId(name)); setFromFollowUps(origin === "Seguimientos"); setSection("Pacientes"); };
  const go = (name: Section) => { setProfile(null); setFromFollowUps(false); showroom.setAutomation({ view: "rules", runId: null }); setSection(name); };
  const local = Object.fromEntries(appNav.map(({ key }) => [key, () => go(key)])) as Record<NavKey, () => void>;
  const breadcrumb = section === "Automatizaciones" && showroom.automation.view === "runs" ? "Historial de actividad" : section;
  return <div className="demo-shell bellis-phase-a bellis-showroom"><aside className="demo-sidebar"><Link className="brand" href="/"><BellisLogo /></Link><div className="workspace-label">ESPACIO DE TRABAJO</div><div className="workspace-card"><span className="workspace-avatar">AL</span><span><b>Dra. Ana López</b><small>Psicología clínica</small></span></div><nav aria-label="Panel profesional">{navItems({ active: section, variant: "sidebar", local })}</nav><div className="demo-side-bottom"><a href="/profesional/ana-lopez"><ExternalLink size={16}/> Ver página pública</a><Link href="/demo/landing">Ver landing demo <ArrowUpRight size={16}/></Link><Link href="/demo/auth">Ver acceso demo <ArrowUpRight size={16}/></Link><Link href="/demo/onboarding">Ver onboarding demo <ArrowUpRight size={16}/></Link><span>Vista de demostración</span></div></aside><div className="demo-content"><AppTopbar breadcrumb={breadcrumb}><DemoBell state={showroom} navigate={setSection}/><a className="demo-top-link" href="/profesional/ana-lopez">Ver página pública <ArrowUpRight size={16}/></a><button className="app-user" aria-label="Ver perfil de demostración" onClick={() => setSection("Perfil")}><span className="app-user-avatar">A</span><span className="app-user-name">Ana</span></button></AppTopbar><AppMobileNav activeKey={section}>{navItems({ active: section, variant: "mobile", local })}<a href="/profesional/ana-lopez">Página pública <ArrowUpRight size={16}/></a><Link href="/demo/landing">Ver landing demo <ArrowUpRight size={16}/></Link><Link href="/demo/auth">Ver acceso demo <ArrowUpRight size={16}/></Link><Link href="/demo/onboarding">Ver onboarding demo <ArrowUpRight size={16}/></Link></AppMobileNav><main className={section === "Resumen" ? "demo-main bellis-dashboard" : section === "Agenda" ? "demo-main bellis-agenda" : "demo-main crm-main"}><div className="demo-notice"><span>Demo interactiva</span> Datos de ejemplo. Los cambios duran durante esta visita.</div>
      {section === "Resumen" && <DemoDashboard state={showroom} appointments={appointments} onAppointment={setSelected} agenda={() => setSection("Agenda")} navigate={setSection}/>}
      {section === "Seguimientos" && <DemoFollowUps state={showroom} patient={(name) => showPatient(name, "Seguimientos")} automation={() => setSection("Automatizaciones")}/>}
      {section === "Automatizaciones" && <DemoAutomations state={showroom} patient={showPatient}/>}
      {section === "Notificaciones" && <DemoNotifications state={showroom} navigate={setSection}/>}
      {section === "Agenda" && <DemoAgenda appointments={appointments}/>}
      {section === "Pacientes" && <DemoPatients state={showroom} profile={profile} setProfile={(id) => { setFromFollowUps(false); setProfile(id); }} fromFollowUps={fromFollowUps} followUps={() => { setProfile(null); setFromFollowUps(false); setSection("Seguimientos"); }} automation={() => setSection("Automatizaciones")}/>}
      {section==="Formularios"&&<QuestionnaireBuilder/>}{section==="Servicios"&&<><div className="demo-title-row"><div><p className="demo-date">TU OFERTA</p><h1>Mis servicios</h1><p>Organizá las sesiones que pueden reservar tus pacientes.</p></div><button className="demo-primary" onClick={()=>setCreated(true)}><Plus size={17}/> Nuevo servicio</button></div><div className="service-list">{services.map((s,i)=><article className="demo-panel service-row" key={s.name}><div className="service-icon"><FileText size={22}/></div><div><h3>{s.name}</h3><p>{s.duration} min · {s.mode}</p></div><strong>{formatMoney(s.price)}</strong><button className={s.active?"status paid":"status muted"} onClick={()=>setServices(services.map((v,j)=>i===j?{...v,active:!v.active}:v))}>{s.active?"Activo":"Inactivo"}</button></article>)}</div></>}
      {section==="Disponibilidad"&&<><div className="demo-title-row"><div><p className="demo-date">TU TIEMPO</p><h1>Disponibilidad</h1><p>Definí los días en que aceptás turnos.</p></div></div><div className="demo-panel settings-panel"><h2>Horario semanal</h2>{["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"].map((d,i)=><label className="day-row" key={d}><input type="checkbox" checked={days[i]} onChange={()=>setDays(days.map((x,j)=>j===i?!x:x))}/><b>{d}</b><span>{days[i]?i===2?"09:00 – 14:00":i===4?"09:00 – 16:00":"09:00 – 18:00":"No disponible"}</span></label>)}<div className="setting-summary"><Clock3 size={18}/> Anticipación mínima: 24 horas · Tiempo entre turnos: 15 minutos</div></div></>}
      {section==="Perfil"&&<><div className="demo-title-row"><div><p className="demo-date">TU ESPACIO</p><h1>Perfil</h1><p>Datos generales de tu perfil profesional.</p></div></div><Tabs label="Secciones del perfil" active={profileTab} onChange={(tab) => { setProfileTab(tab); setSaved(false); }} tabs={[...profileTabs]}/>
        {profileTab === "perfil" && <div role="tabpanel" aria-labelledby="crm-tab-perfil"><div className="demo-panel settings-panel"><h2>Perfil profesional</h2><div className="settings-grid"><label className="field-label">Nombre profesional<input defaultValue="Dra. Ana López"/></label><label className="field-label">Especialidad<input defaultValue="Psicología clínica"/></label><label className="field-label">País<input defaultValue="Argentina"/></label><label className="field-label">Provincia<input defaultValue="Córdoba"/></label><label className="field-label">Ciudad<input defaultValue="Córdoba"/></label><label className="field-label">Moneda<input defaultValue="ARS"/></label><label className="field-label">Zona horaria<input defaultValue="America/Argentina/Buenos_Aires"/></label><label className="field-label">Idioma y formato<input defaultValue="es-AR"/></label></div><button className="demo-primary" onClick={()=>setSaved(true)}>Guardar en la demo</button>{saved&&<p className="success-line"><Check size={17}/> Cambios visibles durante esta sesión.</p>}</div></div>}
        {profileTab === "pagina" && <div role="tabpanel" aria-labelledby="crm-tab-pagina"><div className="demo-panel settings-panel"><h2>Compartí tu link</h2><p className="muted-copy">Página de ejemplo para que tus pacientes reserven.</p><a className="live-link" href="/profesional/ana-lopez">/profesional/ana-lopez</a><div className="setting-summary"><Clock3 size={18}/> Zona horaria: America/Argentina/Buenos_Aires · Moneda: ARS</div></div></div>}
        {profileTab === "cobros" && <div role="tabpanel" aria-labelledby="crm-tab-cobros"><div className="demo-panel settings-panel"><h2>Proveedor de pago</h2><p className="muted-copy">Las transacciones reales requieren conectar un proveedor y confirmar pagos en el servidor.</p><label className="field-label">Método de cobro<select value={paymentProvider} onChange={e=>{setPaymentProvider(e.target.value);setSaved(false)}}><option value="mercado_pago_ar">Mercado Pago Argentina</option><option value="external_link">Link de pago externo</option></select></label>{paymentProvider==="external_link"&&<label className="field-label">Link de pago externo<input value={paymentLink} onChange={e=>{setPaymentLink(e.target.value);setSaved(false)}} placeholder="https://tu-proveedor.com/pago" type="url"/></label>}<button className="demo-primary" onClick={()=>setSaved(true)}>Guardar en la demo</button>{saved&&<p className="success-line"><Check size={17}/> Configuración de ejemplo actualizada para esta sesión.</p>}<div className="provider-row"><span>Mercado Pago Argentina</span><span className="status muted">Integración pendiente</span></div><div className="setting-summary"><ShieldCheckIcon/> Pago obligatorio antes de reservar: activado en el flujo de ejemplo.</div></div></div>}
      </>}
    </main></div><Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="sm:max-w-[540px]"><DialogHeader><DialogTitle>Detalle del turno</DialogTitle></DialogHeader>{selected!==null&&<div className="appointment-detail"><h3>{appointments[selected].name}</h3><p>{appointments[selected].time} · {appointments[selected].service}</p><div><b>Paciente</b><span>{selectedPatient?.email}<br/>{selectedPatient?.phone}</span></div><div><b>Pago</b><span>{appointments[selected].paid?"Pagado ✓":"Pendiente de confirmación"}</span></div><PreconsultationSummary questionnaire={starterQuestionnaire(appointments[selected].service==="Primera consulta"?"service-1":"service-0")} answers={sampleAnswers(appointments[selected].service==="Primera consulta"?"service-1":"service-0")}/><div className="detail-actions"><button onClick={()=>{setAppointments(appointments.map((a,i)=>i===selected?{...a,status:"Completado"}:a));setSelected(null)}}>Marcar completado</button><button onClick={()=>{setAppointments(appointments.map((a,i)=>i===selected?{...a,status:"Cancelado"}:a));setSelected(null)}}>Cancelar turno</button></div></div>}</DialogContent></Dialog><Dialog open={created} onOpenChange={setCreated}><DialogContent><DialogHeader><DialogTitle>Nuevo servicio</DialogTitle></DialogHeader><div className="new-service-form"><label className="field-label">Nombre<input value={newService.name} onChange={e=>setNewService({...newService,name:e.target.value})} placeholder="Consulta inicial"/></label><label className="field-label">Precio (ARS)<input type="number" min="1" value={newService.price} onChange={e=>setNewService({...newService,price:e.target.value})}/></label><label className="field-label">Duración (minutos)<input type="number" min="15" value={newService.duration} onChange={e=>setNewService({...newService,duration:e.target.value})}/></label><label className="field-label">Modalidad<select value={newService.mode} onChange={e=>setNewService({...newService,mode:e.target.value})}><option>Online</option><option>Presencial</option><option>Online y presencial</option></select></label><button className="demo-primary" onClick={addService}>Crear servicio</button></div></DialogContent></Dialog></div>;
}
function sampleAnswers(serviceId: string): QuestionnaireAnswers { const questions=starterQuestionnaire(serviceId).questions; return {[questions[0].id]:"Quiero ayuda con algo puntual",[questions[1].id]:"Ansiedad y manejo del estrés.",[questions[2].id]:["Trabajo","Descanso"],[questions[3].id]:"Dormir mejor y encontrar herramientas para mi día a día."}; }
function ShieldCheckIcon(){return <Check size={18}/>}
