"use client";
import { formatMoney } from "@/lib/market";
import "./demo.css";
import { useState } from "react";
import { CalendarDays, CreditCard, FileText, LayoutDashboard, Settings2, Users, Clock3, ArrowUpRight, Plus, ChevronLeft, ChevronRight, Search, Check, ExternalLink } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { QuestionnaireBuilder } from "./questionnaire-builder";
import { PreconsultationSummary } from "./preconsultation-summary";
import { starterQuestionnaire, type QuestionnaireAnswers } from "@/lib/questionnaires/model";

type Section = "Resumen"|"Agenda"|"Pacientes"|"Servicios"|"Formularios"|"Disponibilidad"|"Cobros"|"Configuración";
type Service = {name:string; price:number; duration:number; mode:string; active:boolean};
const initialServices: Service[] = [{name:"Consulta psicológica",price:25000,duration:60,mode:"Online",active:true},{name:"Primera consulta",price:30000,duration:75,mode:"Online y presencial",active:true},{name:"Sesión de seguimiento",price:22000,duration:50,mode:"Online",active:false}];
const initialAppointments = [{time:"09:00",name:"Mariana López",service:"Consulta psicológica",status:"Confirmado",paid:true},{time:"10:30",name:"Carlos Ruiz",service:"Primera consulta",status:"Confirmado",paid:true},{time:"12:00",name:"Lucía Pérez",service:"Consulta psicológica",status:"Pendiente",paid:false},{time:"15:00",name:"Tomás Méndez",service:"Sesión de seguimiento",status:"Confirmado",paid:true}];
const patients = [{name:"Mariana López",email:"mariana.lopez@email.com",phone:"+54 9 11 4812 9021",last:"17/09/2026",next:"24/09/2026",sessions:7},{name:"Carlos Ruiz",email:"carlos.ruiz@email.com",phone:"+54 9 11 7304 1822",last:"—",next:"24/09/2026",sessions:1},{name:"Lucía Pérez",email:"lucia.perez@email.com",phone:"+54 9 11 2901 3411",last:"10/09/2026",next:"24/09/2026",sessions:3},{name:"Tomás Méndez",email:"tomas.mendez@email.com",phone:"+54 9 11 4512 8400",last:"18/09/2026",next:"24/09/2026",sessions:5}];
const menu: [Section, typeof LayoutDashboard][] = [["Resumen",LayoutDashboard],["Agenda",CalendarDays],["Pacientes",Users],["Servicios",FileText],["Formularios",FileText],["Disponibilidad",Clock3],["Cobros",CreditCard],["Configuración",Settings2]];

export default function Demo(){
  const [section,setSection]=useState<Section>("Resumen"); const [services,setServices]=useState(initialServices); const [appointments,setAppointments]=useState(initialAppointments); const [selected,setSelected]=useState<number|null>(null); const [search,setSearch]=useState(""); const [newService,setNewService]=useState({name:"",price:"",duration:"60",mode:"Online"}); const [created,setCreated]=useState(false); const [days,setDays]=useState([true,true,true,true,true,false,false]); const [paymentLink,setPaymentLink]=useState("");const [paymentProvider,setPaymentProvider]=useState("mercado_pago_ar"); const [saved,setSaved]=useState(false);
  const addService=()=>{if(!newService.name.trim()||Number(newService.price)<=0)return;setServices([...services,{name:newService.name,price:Number(newService.price),duration:Number(newService.duration),mode:newService.mode,active:true}]);setNewService({name:"",price:"",duration:"60",mode:"Online"});setCreated(false)};
  return <div className="demo-shell"><aside className="demo-sidebar"><a className="brand" href="/"><span className="brand-mark">b.</span> bellis</a><div className="workspace-label">ESPACIO DE TRABAJO</div><div className="workspace-card"><span className="workspace-avatar">AL</span><span><b>Dra. Ana López</b><small>Psicología clínica</small></span></div><nav aria-label="Panel profesional">{menu.map(([name,Icon])=><button key={name} className={section===name?"demo-nav active":"demo-nav"} onClick={()=>setSection(name)}><Icon size={19}/>{name}</button>)}</nav><div className="demo-side-bottom"><a href="/profesional/ana-lopez"><ExternalLink size={16}/> Ver página pública</a><span>Vista de demostración</span></div></aside><div className="demo-content"><header className="demo-header"><div><span className="demo-mobile-brand">bellis</span><span className="demo-breadcrumb">Mi espacio <ChevronRight size={14}/> {section}</span></div><a className="demo-top-link" href="/profesional/ana-lopez">Ver página pública <ArrowUpRight size={16}/></a></header><nav className="demo-mobile-nav" aria-label="Secciones">{menu.map(([name])=><button key={name} className={section===name?"active":""} onClick={()=>setSection(name)}>{name}</button>)}</nav><main className="demo-main"><div className="demo-notice"><span>Demo interactiva</span> Los datos mostrados son de ejemplo. Aún no se guardan cuentas ni pagos reales.</div>
      {section==="Resumen"&&<><div className="demo-title-row"><div><p className="demo-date">JUEVES, 24 DE SEPTIEMBRE DE 2026</p><h1>Buen día, Ana <span>✳</span></h1><p>Todo listo para tu jornada de hoy.</p></div><button className="demo-primary" onClick={()=>setSection("Agenda")}>Ver agenda <ArrowUpRight size={17}/></button></div><div className="metric-grid"><Metric label="Turnos de hoy" value="4" detail="3 confirmados" icon={CalendarDays}/><Metric label="Ingresos del día" value="$77.000" detail="ARS confirmados" icon={CreditCard}/><Metric label="Pacientes nuevos" value="1" detail="Esta semana" icon={Users}/><Metric label="Pagos pendientes" value="1" detail="Requiere atención" icon={Clock3}/></div><div className="demo-grid"><section className="demo-panel"><div className="panel-head"><div><h2>Próximos turnos</h2><p>Tu agenda de hoy</p></div><button onClick={()=>setSection("Agenda")}>Ver todas <ChevronRight size={16}/></button></div>{appointments.map((a,i)=><button className="appt-row" key={a.name} onClick={()=>setSelected(i)}><span className="appt-time">{a.time}</span><span className="appt-avatar">{a.name.split(" ").map(v=>v[0]).join("")}</span><span className="appt-details"><b>{a.name}</b><small>{a.service}</small></span><span className={a.paid?"status paid":"status pending"}>{a.paid?"Pagado":"Pendiente"}</span></button>)}</section><section className="demo-panel quick-panel"><div className="panel-head"><div><h2>Tu página de turnos</h2><p>Compartí tu link con tus pacientes</p></div></div><div className="share-preview"><span className="workspace-avatar big">AL</span><h3>Dra. Ana López</h3><p>Psicóloga clínica · Online y presencial</p><a href="/profesional/ana-lopez">Ver mi página pública <ArrowUpRight size={16}/></a></div><div className="mini-insight"><span>Próximos 7 días</span><strong>12 turnos</strong><p>4 pacientes nuevos esta semana</p></div></section></div></>}
      {section==="Agenda"&&<><div className="demo-title-row"><div><p className="demo-date">TU CALENDARIO</p><h1>Mis turnos</h1><p>Revisá turnos, pagos y respuestas previas.</p></div></div><Tabs defaultValue="dia"><TabsList><TabsTrigger value="dia">Día</TabsTrigger><TabsTrigger value="semana">Semana</TabsTrigger><TabsTrigger value="mes">Mes</TabsTrigger></TabsList>{["dia","semana","mes"].map(view=><TabsContent value={view} key={view}><div className="demo-panel calendar-panel"><div className="calendar-toolbar"><button aria-label="Fecha anterior"><ChevronLeft size={18}/></button><strong>{view==="dia"?"Jueves, 24 de septiembre":view==="semana"?"21 – 27 de septiembre":"Septiembre 2026"}</strong><button aria-label="Fecha siguiente"><ChevronRight size={18}/></button></div><div className="calendar-note">Vista de ejemplo · 24 de septiembre de 2026</div>{appointments.map((a,i)=><button className="calendar-item" key={a.name} onClick={()=>setSelected(i)}><span>{a.time}</span><span><b>{a.name}</b><small>{a.service} · {a.status}</small></span><span className={a.paid?"status paid":"status pending"}>{a.paid?"Pagado":"Pendiente"}</span></button>)}</div></TabsContent>)}</Tabs></>}
      {section==="Pacientes"&&<><div className="demo-title-row"><div><p className="demo-date">RELACIONES EN UN SOLO LUGAR</p><h1>Pacientes</h1><p>Información y próximas turnos de cada paciente.</p></div></div><div className="demo-panel"><div className="panel-head"><h2>Todos los pacientes</h2><div className="search-box"><Search size={16}/><Input aria-label="Buscar pacientes" placeholder="Buscar paciente" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>Nombre</TableHead><TableHead>Email</TableHead><TableHead>Teléfono</TableHead><TableHead>Último turno</TableHead><TableHead>Próximo turno</TableHead><TableHead>Sesiones</TableHead></TableRow></TableHeader><TableBody>{patients.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=><TableRow key={p.name}><TableCell className="font-semibold">{p.name}</TableCell><TableCell>{p.email}</TableCell><TableCell>{p.phone}</TableCell><TableCell>{p.last}</TableCell><TableCell>{p.next}</TableCell><TableCell>{p.sessions}</TableCell></TableRow>)}</TableBody></Table></div></div></>}
      {section==="Formularios"&&<QuestionnaireBuilder/>}{section==="Servicios"&&<><div className="demo-title-row"><div><p className="demo-date">TU OFERTA</p><h1>Mis servicios</h1><p>Organizá las sesiones que pueden reservar tus pacientes.</p></div><button className="demo-primary" onClick={()=>setCreated(true)}><Plus size={17}/> Nuevo servicio</button></div><div className="service-list">{services.map((s,i)=><article className="demo-panel service-row" key={s.name}><div className="service-icon"><FileText size={22}/></div><div><h3>{s.name}</h3><p>{s.duration} min · {s.mode}</p></div><strong>{formatMoney(s.price)}</strong><button className={s.active?"status paid":"status muted"} onClick={()=>setServices(services.map((v,j)=>i===j?{...v,active:!v.active}:v))}>{s.active?"Activo":"Inactivo"}</button></article>)}</div></>}
      {section==="Disponibilidad"&&<><div className="demo-title-row"><div><p className="demo-date">TU TIEMPO</p><h1>Disponibilidad</h1><p>Definí los días en que aceptás turnos.</p></div></div><div className="demo-panel settings-panel"><h2>Horario semanal</h2>{["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"].map((d,i)=><label className="day-row" key={d}><input type="checkbox" checked={days[i]} onChange={()=>setDays(days.map((x,j)=>j===i?!x:x))}/><b>{d}</b><span>{days[i]?i===2?"09:00 – 14:00":i===4?"09:00 – 16:00":"09:00 – 18:00":"No disponible"}</span></label>)}<div className="setting-summary"><Clock3 size={18}/> Anticipación mínima: 24 horas · Tiempo entre turnos: 15 minutos</div></div></>}
      {section==="Cobros"&&<><div className="demo-title-row"><div><p className="demo-date">CONFIGURACIÓN DE PAGO</p><h1>Cobros</h1><p>Prepará tu cuenta para cobrar antes de atender.</p></div></div><div className="demo-panel settings-panel"><h2>Proveedor de pago</h2><p className="muted-copy">Las transacciones reales requieren conectar un proveedor y confirmar pagos en el servidor.</p><label className="field-label">Método de cobro<select value={paymentProvider} onChange={e=>{setPaymentProvider(e.target.value);setSaved(false)}}><option value="mercado_pago_ar">Mercado Pago Argentina</option><option value="external_link">Link de pago externo</option></select></label>{paymentProvider==="external_link"&&<label className="field-label">Link de pago externo<input value={paymentLink} onChange={e=>{setPaymentLink(e.target.value);setSaved(false)}} placeholder="https://tu-proveedor.com/pago" type="url"/></label>}<button className="demo-primary" onClick={()=>setSaved(true)}>Guardar en la demo</button>{saved&&<p className="success-line"><Check size={17}/> Configuración de ejemplo actualizada para esta sesión.</p>}<div className="provider-row"><span>Mercado Pago Argentina</span><span className="status muted">Integración pendiente</span></div><div className="setting-summary"><ShieldCheckIcon/> Pago obligatorio antes de reservar: activado en el flujo de ejemplo.</div></div></>}
      {section==="Configuración"&&<><div className="demo-title-row"><div><p className="demo-date">TU ESPACIO</p><h1>Configuración</h1><p>Datos generales de tu perfil profesional.</p></div></div><div className="demo-panel settings-panel"><h2>Perfil profesional</h2><div className="settings-grid"><label className="field-label">Nombre profesional<input defaultValue="Dra. Ana López"/></label><label className="field-label">Especialidad<input defaultValue="Psicología clínica"/></label><label className="field-label">País<input defaultValue="Argentina"/></label><label className="field-label">Provincia<input defaultValue="Córdoba"/></label><label className="field-label">Ciudad<input defaultValue="Córdoba"/></label><label className="field-label">Moneda<input defaultValue="ARS"/></label><label className="field-label">Zona horaria<input defaultValue="America/Argentina/Buenos_Aires"/></label><label className="field-label">Idioma y formato<input defaultValue="es-AR"/></label></div><button className="demo-primary" onClick={()=>setSaved(true)}>Guardar en la demo</button>{saved&&<p className="success-line"><Check size={17}/> Cambios visibles durante esta sesión.</p>}</div></>}
    </main></div><Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="sm:max-w-[540px]"><DialogHeader><DialogTitle>Detalle del turno</DialogTitle></DialogHeader>{selected!==null&&<div className="appointment-detail"><h3>{appointments[selected].name}</h3><p>{appointments[selected].time} · {appointments[selected].service}</p><div><b>Paciente</b><span>{patients[selected].email}<br/>{patients[selected].phone}</span></div><div><b>Pago</b><span>{appointments[selected].paid?"Pagado ✓":"Pendiente de confirmación"}</span></div><PreconsultationSummary questionnaire={starterQuestionnaire(selected===1?"service-1":"service-0")} answers={sampleAnswers(selected===1?"service-1":"service-0")}/><div className="detail-actions"><button onClick={()=>{setAppointments(appointments.map((a,i)=>i===selected?{...a,status:"Completado"}:a));setSelected(null)}}>Marcar completado</button><button onClick={()=>{setAppointments(appointments.map((a,i)=>i===selected?{...a,status:"Cancelado"}:a));setSelected(null)}}>Cancelar turno</button></div></div>}</DialogContent></Dialog><Dialog open={created} onOpenChange={setCreated}><DialogContent><DialogHeader><DialogTitle>Nuevo servicio</DialogTitle></DialogHeader><div className="new-service-form"><label className="field-label">Nombre<input value={newService.name} onChange={e=>setNewService({...newService,name:e.target.value})} placeholder="Consulta inicial"/></label><label className="field-label">Precio (ARS)<input type="number" min="1" value={newService.price} onChange={e=>setNewService({...newService,price:e.target.value})}/></label><label className="field-label">Duración (minutos)<input type="number" min="15" value={newService.duration} onChange={e=>setNewService({...newService,duration:e.target.value})}/></label><label className="field-label">Modalidad<select value={newService.mode} onChange={e=>setNewService({...newService,mode:e.target.value})}><option>Online</option><option>Presencial</option><option>Online y presencial</option></select></label><button className="demo-primary" onClick={addService}>Crear servicio</button></div></DialogContent></Dialog></div>;
}
function sampleAnswers(serviceId: string): QuestionnaireAnswers { const questions=starterQuestionnaire(serviceId).questions; return {[questions[0].id]:"Quiero ayuda con algo puntual",[questions[1].id]:"Ansiedad y manejo del estrés.",[questions[2].id]:["Trabajo","Descanso"],[questions[3].id]:"Dormir mejor y encontrar herramientas para mi día a día."}; }
function Metric({label,value,detail,icon:Icon}:{label:string;value:string;detail:string;icon:typeof CalendarDays}){return <div className="metric-card"><div><span>{label}</span><span className="metric-icon"><Icon size={19}/></span></div><strong>{value}</strong><small>{detail}</small></div>}
function ShieldCheckIcon(){return <Check size={18}/>}
