"use client";
import { ArrowRight, CalendarDays, Check, ChevronRight, Clock3, CreditCard, FileText, Heart, Menu, ShieldCheck, Sparkles, Users } from "lucide-react";
import { useState } from "react";

const steps = [
  ["01", "Tu paciente completa sus datos", "Un formulario previo reúne lo que necesitás saber antes de atender."],
  ["02", "Realiza el pago", "La sesión se paga antes de que se habilite la agenda."],
  ["03", "Elige un horario", "Ve solamente los espacios disponibles según tus reglas."],
  ["04", "Vos recibís todo listo", "La cita, las respuestas y el pago quedan en un solo lugar."],
];
const features = [
  [CalendarDays, "Agenda online"], [CreditCard, "Cobros antes de atender"], [FileText, "Formularios previos"],
  [Clock3, "Recordatorios automáticos"], [Heart, "Página profesional"], [Users, "Gestión de pacientes"],
  [Sparkles, "Servicios y precios"], [ShieldCheck, "Disponibilidad personalizada"], [CalendarDays, "Historial de citas"],
] as const;

export default function Home() {
  const [menu, setMenu] = useState(false);
  return <main>
    <header className="site-header"><a className="brand" href="/"><span className="brand-mark">b.</span> bellis</a><nav className={menu ? "nav open" : "nav"}><a href="#como-funciona" onClick={() => setMenu(false)}>Cómo funciona</a><a href="#funciones" onClick={() => setMenu(false)}>Funciones</a><a href="#precios" onClick={() => setMenu(false)}>Precios</a><a href="/demo" className="nav-demo">Explorar demo</a></nav><div className="header-actions"><a href="/registro" className="button button-dark">Crear mi cuenta gratis <ArrowRight size={17}/></a><button className="menu-toggle" aria-label="Abrir menú" onClick={() => setMenu(!menu)}><Menu size={23}/></button></div></header>
    <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> La forma simple de atender mejor</div><h1>Tu agenda. Tus pacientes. Tus pagos. <em>Todo en un solo lugar.</em></h1><p>Dejá que tus pacientes completen su información, paguen y agenden solos. Vos recibís todo listo antes de atender.</p><div className="hero-actions"><a href="/registro" className="button button-dark">Crear mi cuenta gratis <ArrowRight size={18}/></a><a href="#como-funciona" className="button button-light">Ver cómo funciona <ChevronRight size={18}/></a></div><div className="hero-trust"><span><Check size={16}/> 30 días gratis</span><span><Check size={16}/> Sin tarjeta</span><span><Check size={16}/> Sin compromiso</span></div></div><div className="hero-visual" aria-label="Vista previa de la agenda Bellis"><div className="preview-top"><span className="preview-brand"><span className="brand-mark mini">b.</span> bellis</span><span className="preview-chip">Panel profesional</span></div><div className="preview-body"><div className="preview-side"><span className="side-title">TU ESPACIO</span><span className="side-active"><CalendarDays size={17}/> Resumen</span><span><CalendarDays size={17}/> Agenda</span><span><Users size={17}/> Pacientes</span><span><CreditCard size={17}/> Cobros</span></div><div className="preview-main"><div className="preview-heading"><div><small>MIÉRCOLES, 24 DE SEPTIEMBRE</small><h3>Buen día, Ana <span>✳</span></h3></div><span className="avatar">AL</span></div><div className="preview-stats"><div><small>Citas de hoy</small><strong>05</strong><span>2 por atender</span></div><div><small>Ingresos del día</small><strong>$3,000</strong><span>MXN confirmados</span></div></div><div className="preview-list"><div className="list-head"><b>Próximas citas</b><span>Ver agenda →</span></div><div className="appointment"><span className="time">10:00</span><span className="person-dot lilac">ML</span><span><b>Mariana López</b><small>Consulta psicológica · 60 min</small></span><span className="paid">Pagado</span></div><div className="appointment"><span className="time">11:30</span><span className="person-dot peach">CR</span><span><b>Carlos Ruiz</b><small>Primera consulta · 75 min</small></span><span className="paid">Pagado</span></div></div></div></div><div className="float-card"><span className="float-icon"><Check size={16}/></span><span><b>Nueva cita confirmada</b><small>Todo listo para tu próxima sesión</small></span></div></div></section>
    <section className="logo-strip wrap"><p>Más tiempo para tus pacientes. Menos tiempo coordinando.</p><div>PSICOLOGÍA <span>·</span> ODONTOLOGÍA <span>·</span> KINESIOLOGÍA <span>·</span> NUTRICIÓN</div></section>
    <section id="como-funciona" className="steps-section"><div className="wrap"><div className="section-intro"><span className="kicker">CÓMO FUNCIONA</span><h2>De un mensaje a una cita lista para atender.</h2><p>Un recorrido claro para tu paciente. Toda la información organizada para vos.</p></div><div className="steps-grid">{steps.map(([number,title,description]) => <article className="step-card" key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{description}</p><ArrowRight size={19}/></article>)}</div></div></section>
    <section id="funciones" className="features-section wrap"><div className="section-intro"><span className="kicker">TODO CONECTADO</span><h2>Todo lo que necesitás para dejar de perseguir mensajes.</h2><p>De la primera consulta al historial del paciente, cada paso vive en Bellis.</p></div><div className="features-grid">{features.map(([Icon,title]) => <div className="feature-card" key={title}><span><Icon size={22} strokeWidth={1.8}/></span><h3>{title}</h3></div>)}</div></section>
    <section className="professions-section"><div className="wrap professions-inner"><div><span className="kicker">HECHO PARA VOS</span><h2>Para profesionales que trabajan por cita.</h2><p>Configurá tus servicios, preguntas y disponibilidad a tu manera. Bellis se adapta a tu forma de atender.</p></div><div className="profession-tags">{["Psicología", "Odontología", "Kinesiología", "Nutrición", "Psicopedagogía", "Otros"].map(x=><span key={x}>{x}</span>)}</div></div></section>
    <section id="precios" className="pricing-section wrap"><div className="pricing-card"><div><span className="kicker">EMPEZÁ HOY</span><h2>Tu consultorio más simple comienza acá.</h2><p>Probá Bellis durante 30 días y descubrí cuánto tiempo podés recuperar cada semana.</p><div className="pricing-points"><span><Check size={17}/> 30 días gratis</span><span><Check size={17}/> Sin tarjeta</span><span><Check size={17}/> Sin compromiso</span></div></div><div className="pricing-action"><span>Prueba gratuita</span><strong>30 días</strong><small>Planes para profesionales y consultorios próximamente.</small><a href="/registro" className="button button-dark">Activar mi cuenta gratis <ArrowRight size={18}/></a></div></div></section>
    <footer><div className="wrap footer-inner"><span className="brand"><span className="brand-mark">b.</span> bellis</span><span>Más tiempo para lo que importa.</span><span>© 2026 Bellis</span></div></footer>
  </main>;
}
